### PR TITLE
Update messages.json RUS

### PR DESCRIPTION
**Pull request by wvxwxvw**

### CODE REVIEW

**Comment by fastaddons** [comment]
Hello,
Thank you for the update!
However, there are issues, for example message "o_about_intro" lost it's placeholders.
**What tool did you used for generating this file?**
Also, it would be nice to keep the indent to 2 spaces so that the diff is nicer...

**Comment by wvxwxvw** [comment]
@fastaddons 
Hi.
I use npp++ for encoding and tabulation, and Beyond Compare for comparison. I removed the fillers myself, deciding they weren't needed. And I fixed the indents myself, otherwise everything is "blue" in Beyond Compare. Translation files should not be indented, as this is a hassle for translators.  
  
I can create a new query with placeholders. ?

**Comment by fastaddons** [comment]
It would be best to keep the original styling and indentation and change only the lines with translations.
So that the diff here is easy to check.
Just make the changes in the file if you know how and add new commit or new pull request, whatever is easier for you.

**Comment by wvxwxvw** [comment]
`"common": true` In, for example,
`````
  "_description_recent_features": {
    "message": "Recently added features:",
    "common": true
  },
`````
should I keep it?  
I am guided by the English file.

**Comment by fastaddons** [comment]
Wait, I need to think :).
So, you've used the EN file because the existing file was missing messages, right?
I didn't realize that at all, so people can't really translate things because the keys are missing... oh, that's my bad.

Anyway, yes, you should keep the "common" key.
But I still need to think how to make this easier...

**Comment by wvxwxvw** [comment]
Я не делал еще коммитов. [Вот так нормально](https://github.com/fastaddons/locales/commit/51ee84282f0d7fea6a1cca07b86e655adbdab595#commitcomment-85818853).

**Comment by fastaddons** [comment]
It's almost OK, there are still few placeholders missing.

**Pull request closed without merging**
